### ISSUE TITLE
An error during "bun install," how can I resolve it?

### ISSUE THREAD

**Issue by tomy2502** [n4ze3m/page-assist#247]
OS: Ubuntu 24.04 LTS (GNU/Linux 6.8.0-31-generic x86_64)

(base) root@kafeizha:# bun install
bun install v1.1.34 (5e5e7c60)

$ wxt prepare

WXT 0.19.13                                                                                                                                                   9:05:36 AM
✖ Command failed after 466 ms                                                                                                                                9:05:37 AM

 ERROR  virtualModule.require is not a function. (In 'virtualModule.require(wantedModuleName)', 'virtualModule.require' is undefined)                         9:05:37 AM

  at <anonymous> (node_modules/vite-plugin-top-level-await/dist/esbuild.js:14:50)
  at <anonymous> (node_modules/vite-plugin-top-level-await/dist/esbuild.js:16:56)
  at evalModule (node_modules/jiti/dist/jiti.js:1:247312)
  at jiti (node_modules/jiti/dist/jiti.js:1:245240)
  at <anonymous> (node_modules/vite-plugin-top-level-await/dist/index.js:25:32)
  at evalModule (node_modules/jiti/dist/jiti.js:1:247312)
  at jiti (node_modules/jiti/dist/jiti.js:1:245240)
  at <anonymous> (node_modules/vite-plugin-top-level-await/exports/require.cjs:1:100)
  at evalModule (node_modules/jiti/dist/jiti.js:1:247312)
  at jiti (node_modules/jiti/dist/jiti.js:1:245240)
  at <anonymous> (wxt.config.ts:3:1)
  at evalModule (node_modules/jiti/dist/jiti.js:1:247312)
  at jiti (node_modules/jiti/dist/jiti.js:1:245240)
  at <anonymous> (node_modules/c12/dist/shared/c12.cab0c9da.mjs:345:26)
  at resolveConfig (node_modules/c12/dist/shared/c12.cab0c9da.mjs:279:30)
  at <anonymous> (node_modules/c12/dist/shared/c12.cab0c9da.mjs:147:29)
  at loadConfig (node_modules/c12/dist/shared/c12.cab0c9da.mjs:108:27)
  at <anonymous> (node_modules/wxt/dist/core/resolve-config.mjs:17:57)
  at resolveConfig (node_modules/wxt/dist/core/resolve-config.mjs:13:37)
  at <anonymous> (node_modules/wxt/dist/core/wxt.mjs:11:24)
  at registerWxt (node_modules/wxt/dist/core/wxt.mjs:8:35)
  at <anonymous> (node_modules/wxt/dist/core/prepare.mjs:5:9)
  at prepare (node_modules/wxt/dist/core/prepare.mjs:4:31)
  at <anonymous> (node_modules/wxt/dist/cli/commands.mjs:76:11)
  at <anonymous> (node_modules/wxt/dist/cli/commands.mjs:75:21)
  at <anonymous> (node_modules/wxt/dist/cli/cli-utils.mjs:17:28)
  at <anonymous> (node_modules/wxt/dist/cli/cli-utils.mjs:9:10)
  at module code (node_modules/wxt/dist/cli/index.mjs:11:11)
  at <anonymous> (native)
  at processTicksAndRejections (native)

error: postinstall script from "pageassist" exited with 1

**Comment by n4ze3m** [comment]
Hey, can you check with Node.js? I don't know what the issue is. I just checked on Ubuntu, and it's working fine for me

**Comment by scubanarc** [comment]
Same issue here

**Comment by n4ze3m** [comment]
Hey, sorry about the issue. Are you using Bun or npm?

**Comment by scubanarc** [comment]
Using bun. However, after I posted this I used nvm to install node 23, and the problem disappeared. Somehow that fixed it.

**Comment by scubanarc** [comment]
More info for you. This is on Mint 22. Before I used nvm I didn't have any versions of node installed. So mostly vanilla install with no node, running the 'bun install' command failed.

Install nvm, install node 23, all problems gone.

It seems like some version of node has to be installed for 'bun install' to work.

**Comment by interpidtjuniversity** [comment]
install node and this will be ok
